// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4foICtMoPT0NFIVlKudsXfrJ2501Rkqc',
    appId: '1:330428956073:web:0dcd52b2784c026dcf98b8',
    messagingSenderId: '330428956073',
    projectId: 'learning-priyanshuuuyadav',
    authDomain: 'learning-priyanshuuuyadav.firebaseapp.com',
    storageBucket: 'learning-priyanshuuuyadav.appspot.com',
    measurementId: 'G-1W8NHE0V5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDPzDiCfVEvG-6sXTCw9mlWOawsNtN8BA',
    appId: '1:330428956073:android:b4a3a1de49c8a2c9cf98b8',
    messagingSenderId: '330428956073',
    projectId: 'learning-priyanshuuuyadav',
    storageBucket: 'learning-priyanshuuuyadav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlPogYuL41gazYHYHQWvRvnHnK3ZWF7NU',
    appId: '1:330428956073:ios:1423ff91f1072e0dcf98b8',
    messagingSenderId: '330428956073',
    projectId: 'learning-priyanshuuuyadav',
    storageBucket: 'learning-priyanshuuuyadav.appspot.com',
    iosBundleId: 'com.appignmentapp.appignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlPogYuL41gazYHYHQWvRvnHnK3ZWF7NU',
    appId: '1:330428956073:ios:1423ff91f1072e0dcf98b8',
    messagingSenderId: '330428956073',
    projectId: 'learning-priyanshuuuyadav',
    storageBucket: 'learning-priyanshuuuyadav.appspot.com',
    iosBundleId: 'com.appignmentapp.appignmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4foICtMoPT0NFIVlKudsXfrJ2501Rkqc',
    appId: '1:330428956073:web:97e8f687d60c6d9ccf98b8',
    messagingSenderId: '330428956073',
    projectId: 'learning-priyanshuuuyadav',
    authDomain: 'learning-priyanshuuuyadav.firebaseapp.com',
    storageBucket: 'learning-priyanshuuuyadav.appspot.com',
    measurementId: 'G-ZWS5YB6TC9',
  );
}
